### ISSUE TITLE
Translate -999 to `NA`

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/azmetr#12]
It looks like missing values are coded as `-999` or `-9999` or `-99999` in the data.  These should be converted to `NA`

**Comment by jeremylweiss** [comment]
Right, nodata values should be converted to NA within an R environment.

Values are coded as -999 or -9999 or -99999 in the data, but this only is correct for data since September 28, 2022.

Prior to that date, and since 2020-12-30, nodata values in the new API database are represented by -7999.

Nodata values are different in the legacy database (that is, data prior to 2020-12-30).


From: Eric R. Scott ***@***.***>
Sent: Monday, October 17, 2022 3:51 PM
To: cct-datascience/azmetr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT][cct-datascience/azmetr] Translate -999 to `NA` (Issue #12)


External Email

It looks like missing values are coded as -999 or -9999 or -99999 in the data. These should be converted to NA

**Comment by Aariq** [comment]
Thanks!  I added -7999 to the list in PR #15
